export const pubs = [
	{
		imgUser: "https://unavatar.io/twitter/almeidacabron",
		userName: "Almeida Cabron",
		subUserName: "@almeidacabron",
		isVerified: true,
		pubDate: "10h",
		commentPub: "Hola, @almeidacabron, ¿que tal?",
		numComments: 10,
		numLikes: 10,
		numRetweets: 10,
		numViews: 10,
	},
	{
		imgUser: "https://unavatar.io/twitter/almeidacabron",
		userName: "Almeida Cabron",
		subUserName: "@almeidacabron",
		isVerified: true,
		pubDate: "10h",
		commentPub: "Hola, @almeidacabron, ¿que tal?",
		numComments: 10,
		numLikes: 10,
		numRetweets: 10,
		numViews: 10,
	},
	{
		imgUser: "https://unavatar.io/twitter/almeidacabron",
		userName: "Almeida Cabron",
		subUserName: "@almeidacabron",
		isVerified: true,
		pubDate: "10h",
		commentPub: "Hola, @almeidacabron, ¿que tal?",
		numComments: 10,
		numLikes: 10,
		numRetweets: 10,
		numViews: 10,
	},
	{
		imgUser: "https://unavatar.io/twitter/almeidacabron",
		userName: "Almeida Cabron",
		subUserName: "@almeidacabron",
		isVerified: true,
		pubDate: "10h",
		commentPub: "Hola, @almeidacabron, ¿que tal?",
		numComments: 10,
		numLikes: 10,
		numRetweets: 10,
		numViews: 10,
	},
	{
		imgUser: "https://unavatar.io/twitter/almeidacabron",
		userName: "Almeida Cabron",
		subUserName: "@almeidacabron",
		isVerified: true,
		pubDate: "10h",
		commentPub: "Hola, @almeidacabron, ¿que tal?",
		numComments: 10,
		numLikes: 10,
		numRetweets: 10,
		numViews: 10,
	},
	{
		imgUser: "https://unavatar.io/twitter/almeidacabron",
		userName: "Almeida Cabron",
		subUserName: "@almeidacabron",
		isVerified: true,
		pubDate: "10h",
		commentPub: "Hola, @almeidacabron, ¿que tal?",
		numComments: 10,
		numLikes: 10,
		numRetweets: 10,
		numViews: 10,
	},
];
